language: python
python:
  - "2.7_with_system_site_packages"

# Addons for travis
addons:
    postgresql: "9.3"

before_install:
    - sudo apt-get install -qq build-essential net-tools python python-dev python-numpy python-scipy python-psycopg2

# command to install dependencies
install: "pip install --requirement requirements.txt"

# commands to run before the tests
before_script:
    - createdb $PGDATABASE
    - cp config/config_travis.json config/config.json
    - psql -f sql/create.sql -d ga_runner_testing
    - python -c "from GATools.db.create import create; myc=create(config_file='config/config.json'); myc.insert_networks()"
# command to run tests
script:
    - nosetests
    - python -m scoop ga_runner.py --script-mode -r 5 -g 10 --variation 2 -s 1 --tournament-size 10 1 20 40 10 1
    - python -m scoop ga_runner.py --script-mode -r 5 -g 10 --variation 2 -s 3 1 20 40 10 1
    - python -m scoop ga_runner.py --script-mode -r 5 -g 10 -s 2 1 20 40 10 1
    - python -m scoop ga_runner.py --script-mode -r 5 -g 10 -s 2 2 20 40 10 1
    - python -m scoop ga_runner.py --script-mode -r 5 -g 5000 --variation 3 -g 5000 -s 3 1 30 60 20 1

