language: python
python:
  - "2.7"
  - "3.4"
# Addons for travis
addons:
    postgresql: "9.3"

before_install:
    - sudo apt-get install build-essential net-tools python python-dev libpq-dev libblas-dev liblapack-dev

# command to install dependencies
install: "pip install -r requirements.txt"
# environment variables
env: PGHOST=localhost PGDATABASE=ga_runner_testing PGUSER=postgres PGPASSWORD=
# commands to run before the tests
before_script:
    - psql -c 'create database ga_runner_testing;' -U postgres
    - psql -f sql/create.sql
    - python -c "from GATools.db.create import create; myc=create(); myc.insert_networks()"
# command to run tests
script:
    - nosetests
    - python -m scoop ga_runner.py -r 5 -g 10 --variation 2 -s 1 --tournament-size 10 1 20 40 10 1
    - python -m scoop ga_runner.py -r 5 -g 10 --variation 2 -s 3 1 20 40 10 1
    - python -m scoop ga_runner.py -r 5 -g 10 -s 2 1 20 40 10 1
    - python -m scoop ga_runner.py -r 5 -g 10 -s 2 2 20 40 10 1
